/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DiaryEntry } from "./DiaryEntry";
import { DiaryEntryCountArgs } from "./DiaryEntryCountArgs";
import { DiaryEntryFindManyArgs } from "./DiaryEntryFindManyArgs";
import { DiaryEntryFindUniqueArgs } from "./DiaryEntryFindUniqueArgs";
import { CreateDiaryEntryArgs } from "./CreateDiaryEntryArgs";
import { UpdateDiaryEntryArgs } from "./UpdateDiaryEntryArgs";
import { DeleteDiaryEntryArgs } from "./DeleteDiaryEntryArgs";
import { FoodFindManyArgs } from "../../food/base/FoodFindManyArgs";
import { Food } from "../../food/base/Food";
import { WorkoutFindManyArgs } from "../../workout/base/WorkoutFindManyArgs";
import { Workout } from "../../workout/base/Workout";
import { User } from "../../user/base/User";
import { DiaryEntryService } from "../diaryEntry.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DiaryEntry)
export class DiaryEntryResolverBase {
  constructor(
    protected readonly service: DiaryEntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "read",
    possession: "any",
  })
  async _diaryEntriesMeta(
    @graphql.Args() args: DiaryEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DiaryEntry])
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "read",
    possession: "any",
  })
  async diaryEntries(
    @graphql.Args() args: DiaryEntryFindManyArgs
  ): Promise<DiaryEntry[]> {
    return this.service.diaryEntries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DiaryEntry, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "read",
    possession: "own",
  })
  async diaryEntry(
    @graphql.Args() args: DiaryEntryFindUniqueArgs
  ): Promise<DiaryEntry | null> {
    const result = await this.service.diaryEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DiaryEntry)
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "create",
    possession: "any",
  })
  async createDiaryEntry(
    @graphql.Args() args: CreateDiaryEntryArgs
  ): Promise<DiaryEntry> {
    return await this.service.createDiaryEntry({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DiaryEntry)
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "update",
    possession: "any",
  })
  async updateDiaryEntry(
    @graphql.Args() args: UpdateDiaryEntryArgs
  ): Promise<DiaryEntry | null> {
    try {
      return await this.service.updateDiaryEntry({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DiaryEntry)
  @nestAccessControl.UseRoles({
    resource: "DiaryEntry",
    action: "delete",
    possession: "any",
  })
  async deleteDiaryEntry(
    @graphql.Args() args: DeleteDiaryEntryArgs
  ): Promise<DiaryEntry | null> {
    try {
      return await this.service.deleteDiaryEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Food], { name: "foods" })
  @nestAccessControl.UseRoles({
    resource: "Food",
    action: "read",
    possession: "any",
  })
  async findFoods(
    @graphql.Parent() parent: DiaryEntry,
    @graphql.Args() args: FoodFindManyArgs
  ): Promise<Food[]> {
    const results = await this.service.findFoods(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Workout], { name: "workouts" })
  @nestAccessControl.UseRoles({
    resource: "Workout",
    action: "read",
    possession: "any",
  })
  async findWorkouts(
    @graphql.Parent() parent: DiaryEntry,
    @graphql.Args() args: WorkoutFindManyArgs
  ): Promise<Workout[]> {
    const results = await this.service.findWorkouts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: DiaryEntry): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
